# Generated by Django 4.2.1 on 2023-05-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_trainee_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("F", "Candidate"),
                    ("T", "Trainee"),
                    ("M", "Mentor"),
                    ("P", "Personnel"),
                    ("C", "Curator"),
                    ("A", "Admin"),
                ],
                max_length=1,
            ),
        ),
    ]
