# Generated by Django 4.2.1 on 2023-05-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_age_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="age",
        ),
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
