# Generated by Django 4.2.1 on 2023-05-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_department"),
        ("accounts", "0006_remove_user_age_remove_user_gender"),
    ]

    operations = []
