# Generated by Django 4.2.1 on 2023-05-24 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_traineeprofile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="traineeprofile",
            name="cv_score",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
        migrations.AddField(
            model_name="traineeprofile",
            name="test_score",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(100)]
            ),
        ),
    ]
