# Generated by Django 4.2.1 on 2023-05-26 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_education_degree"),
    ]

    operations = [
        migrations.AddField(
            model_name="traineeprofile",
            name="career_school_password",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Career School Password",
            ),
        ),
        migrations.AddField(
            model_name="traineeprofile",
            name="career_school_username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Career School Login",
            ),
        ),
        migrations.AddField(
            model_name="traineeprofile",
            name="progress_career_school",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="traineeprofile",
            name="testing_platform_password",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Testing platform Password",
            ),
        ),
        migrations.AddField(
            model_name="traineeprofile",
            name="testing_platform_username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Testing platform Login",
            ),
        ),
    ]
