# Generated by Django 4.2.1 on 2023-05-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_traineeprofile_career_school_password_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="traineeprofile",
            old_name="status",
            new_name="test_status",
        ),
    ]
