version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      PGDATA: "/var/lib/postgresql/data/pgdata"

volumes:
  app-db-data: {}
