# Generated by Django 4.2.1 on 2023-05-27 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("internship", "0013_workplace_department"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="work_place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="internship.workplace",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
