domain: leaders.rubles.lol

postgres_db: app

allowed_hosts: "{{domain}} {{ansible_host}} localhost 127.0.0.1 localhost:3000 127.0.0.1:3000 127.0.0.1:5173"
csrf_trusted_origins: "https://{{domain}} http://localhost http://localhost:3000 http://localhost:5173 http://127.0.0.1:5173"
server_host: https://{{domain}}
app_image_version: feature-ci
