# Generated by Django 4.2.1 on 2023-05-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internshipapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("next_stage", "Approved for next stage"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
