# Generated by Django 4.2.1 on 2023-05-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship", "0002_alter_internship_application_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
