# Generated by Django 4.2.1 on 2023-05-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship", "0004_qualification_vacancy"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipapplication",
            name="is_recommended",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
