# Generated by Django 4.2.1 on 2023-05-21 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("internship", "0005_internshipapplication_is_recommended"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="is_published",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_vacancies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
