# Generated by Django 4.2.1 on 2023-05-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_department"),
        ("internship", "0006_remove_vacancy_approved_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Тестовое задание", max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Text")], default="text", max_length=50
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_tasks",
                        to="accounts.department",
                        verbose_name="Owned by department",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Test tasks",
                "db_table": "internship_test_task",
            },
        ),
        migrations.AddField(
            model_name="vacancy",
            name="test_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="internship.testtask",
                verbose_name="Test task",
            ),
        ),
    ]
