# Generated by Django 4.2.1 on 2023-05-21 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internship", "0007_test_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="internshipapplication",
            name="direction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="internship.direction",
            ),
        ),
    ]
