# Generated by Django 4.2.1 on 2023-05-21 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_department"),
        ("internship", "0007_test_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="VacancyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_answer", models.TextField()),
                (
                    "covering_letter",
                    models.TextField(
                        blank=True, null=True, verbose_name="Covering letter"
                    ),
                ),
                (
                    "approved_by_mentor",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Approved by mentor"
                    ),
                ),
                (
                    "approved_by_applicant",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Approved by applicant"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.traineeprofile",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="internship.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vacancy responses",
                "db_table": "internship_vacancy_response",
                "unique_together": {("vacancy", "applicant")},
            },
        ),
    ]
