# Generated by Django 4.2.1 on 2023-05-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internship", "0007_internshipapplication_direction"),
        ("internship", "0007_test_task"),
    ]

    operations = []
