# Generated by Django 4.2.1 on 2023-05-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_traineeprofile_career_school_password_and_more"),
        ("internship", "0012_alter_internshipapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workplace",
            name="department",
            field=models.ForeignKey(
                default=219165,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.department",
                verbose_name="Department",
            ),
            preserve_default=False,
        ),
    ]
