# Generated by Django 4.2.1 on 2023-05-28 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("internship", "0013_workplace_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentor_of",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Mentor",
            ),
        ),
    ]
